const FoodList = [
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0dd",
        "label":
            "apples",
        "nutrients":
        {
            "ENERC_KCAL":
                52,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0cc",
        "label":
            "rice",
        "nutrients":
        {
            "ENERC_KCAL":
                300,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0bb",
        "label":
            "chicken",
        "nutrients":
        {
            "ENERC_KCAL":
                100,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0aa",
        "label":
            "bread",
        "nutrients":
        {
            "ENERC_KCAL":
                60,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0zz",
        "label":
            "broccoli",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0vv",
        "label":
            "potatoes",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0pp",
        "label":
            "tomatoes",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0xx",
        "label":
            "carrots",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "food_a1gb9ubb72c7snbuxr3weagwv0yy",
        "label":
            "banans",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
]

export default FoodList;