const FoodList = [
    {
        "foodId":
            "1",
        "label":
            "apples",
        "nutrients":
        {
            "ENERC_KCAL":
                52,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "2",
        "label":
            "rice",
        "nutrients":
        {
            "ENERC_KCAL":
                300,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "3",
        "label":
            "chicken",
        "nutrients":
        {
            "ENERC_KCAL":
                100,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "4",
        "label":
            "bread",
        "nutrients":
        {
            "ENERC_KCAL":
                60,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "5",
        "label":
            "broccoli",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "6",
        "label":
            "potatoes",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "7",
        "label":
            "tomatoes",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "8",
        "label":
            "carrots",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
    {
        "foodId":
            "9",
        "label":
            "banans",
        "nutrients":
        {
            "ENERC_KCAL":
                25,
            "PROCNT":
                0.26,
            "FAT":
                0.17,
            "CHOCDF":
                13.81,
            "FIBTG":
                2.4
        },
    },
]

export default FoodList;