name: Build, Test on merge
'on':
  push:
    branches:
      - main
jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
